### ISSUE TITLE
Error for Add any Rss

### ISSUE THREAD

**Issue by norm-git** [danimart1991/jackett2telegram#4]
when I try to add a Rss URL, It does not save it

The same happens with Rss of CineCalidad

`2021-10-18 02:18:05,582 - root - INFO - List: Indexer Nyaas | https://nyaa.si/rss added.
2021-10-18 02:18:43,482 - apscheduler.executors.default - INFO - Running job "rss_monitor (trigger: interval[0:01:00], next run at: 2021-10-18 02:18:43 UTC)" (scheduled at 2021-10-18 02:18:43.478241+00:00)
2021-10-18 02:18:45,351 - root - ERROR - Indexer not available due to some issue: Nyaas
Traceback (most recent call last):
  File "jackett2telegram.py", line 220, in rss_monitor
    jackettitem_to_telegram(context, item, rss_name)
  File "jackett2telegram.py", line 314, in jackettitem_to_telegram
    category = item.find('category').text
AttributeError: 'NoneType' object has no attribute 'text'`

**Comment by norm-git** [comment]
> Hello @norm-git
> 
> Please read the documentation. This repository only works with RSS generated using Jackett.

is true
